#!/usr/bin/python3
from brownie import RoboCollectible, accounts, network, config
from scripts.utilities import OPENSEA_FORMAT
from scripts.get_robo_img import execute
from scripts.upload_to_pinata import upload_binary
import json

IPFS_PREFIX = "https://ipfs.io/ipfs/"

metadata_template = {
    "name": "",
    "description": "",
    "image": "",
    "attributes": [{"trait_type": "uniqueness", "value": 99.9999999}, {"trait_type": "coolness", "value": 100}],
}


def main():
    dev = accounts.add(config["wallets"]["from_key"])
    print(network.show_active())
    collectible = RoboCollectible[len(RoboCollectible) - 1]
    token_id = collectible.tokenCounter()
    uri = create_token_uri(token_id)
    transaction = collectible.createCollectible(uri, {"from": dev})
    transaction.wait(1)
    print(
        "Awesome! You can view your NFT at {}".format(
            OPENSEA_FORMAT.format(collectible.address, token_id)
        )
    )
    print('Please give up to 20 minutes, and hit the "refresh metadata" button')


def create_token_uri(token_id):
    t_id_str = str(token_id)
    img = execute("unique robot image from token " + t_id_str)
    name = "lovely-robot-" + t_id_str + ".png"
    ipfs_hash = upload_binary(img, name)
    metadata_template["name"] = "Lovely Robot #" + t_id_str
    metadata_template["description"] = "A unique robot generated by lovely RoboHash.org especially for YOU."
    metadata_template["image"] = IPFS_PREFIX + ipfs_hash + "?filename=" + name
    json_str = json.dumps(metadata_template)
    meta_name = "lovely-robot-" + t_id_str + ".json"
    meta_hash = upload_binary(json_str, meta_name)
    return IPFS_PREFIX + meta_hash + "?filename=" + meta_name